export const Plus = () => <span>+</span>
export const RefreshCw = () => <span>↻</span>
export const Activity = () => <span>📊</span>
export const TrendingUp = () => <span>📈</span>
export const TrendingDown = () => <span>📉</span>
export const BarChart3 = () => <span>📊</span>
export const Settings = () => <span>⚙️</span>
export const Target = () => <span>🎯</span>
export const History = () => <span>📜</span>
export const DollarSign = () => <span>💲</span>
export const Clock = () => <span>🕐</span>
export const X = () => <span>✕</span>
export const CheckCircle = () => <span>✅</span>
export const AlertCircle = () => <span>⚠️</span>
export const Trash2 = () => <span>🗑️</span>
export const ChevronDown = () => <span>▼</span>
export const ChevronRight = () => <span>▶</span>
export const Filter = () => <span>🔍</span>
export const RotateCcw = () => <span>↺</span>
export const Users = () => <span>👥</span>
export const Zap = () => <span>⚡</span>
export const Database = () => <span>🗄️</span>
export const PieChart = () => <span>🥧</span>
export const Calculator = () => <span>🧮</span>
export const Cog = () => <span>⚙️</span>
export const Bell = () => <span>🔔</span>
export const Shield = () => <span>🛡️</span>
export const Eye = () => <span>👁️</span>
export const EyeOff = () => <span>🙈</span>
export const Wifi = () => <span>📶</span>
export const WifiOff = () => <span>📵</span>
export const AlertTriangle = () => <span>⚠️</span>
export const CalendarIcon = () => <span>📅</span>
export const ArrowUpDown = () => <span>↕️</span>
export const ArrowUp = () => <span>↑</span>
export const ArrowDown = () => <span>↓</span>
export const PieChartIcon = () => <span>🥧</span>

export const Info = () => <span>ℹ️</span>
export const Home = () => <span>🏠</span>
export const Monitor = () => <span>🖥️</span>
export const Layers = () => <span>📚</span>
