// Define Settings type for better type safety
export interface Settings {
  base_volume_factor: number
  positions_average: number
  max_leverage: number
  negativeChangePercent: number
  leveragePercentage: number
  prehistoricDataDays: number
  marketTimeframe: number
  tradeIntervalSeconds: number
  realPositionsIntervalSeconds: number
  validationTimeoutSeconds: number
  mainTradeInterval: number
  presetTradeInterval: number
  positionCost: number
  useMaximalLeverage: boolean
  baseValueRangeMin: number
  baseValueRangeMax: number
  baseRatioMin: number
  baseRatioMax: number
  trailingOption: boolean
  previousPositionsCount: number
  lastStateCount: number
  trailingEnabled: boolean
  trailingStartValues: string
  trailingStopValues: string
  blockAdjustment: boolean
  dcaAdjustment: boolean
  arrangementType: string
  numberOfSymbolsToSelect: number
  quoteAsset: string
  baseProfitFactor: number
  mainProfitFactor: number
  realProfitFactor: number
  trailingStopLoss: boolean
  maxDrawdownTimeHours: number
  mainEngineIntervalMs: number
  presetEngineIntervalMs: number
  activeOrderHandlingIntervalMs: number
  databaseSizeBase: number
  databaseSizeMain: number
  databaseSizeReal: number
  databaseSizePreset: number
  positionCooldownMs: number
  maxPositionsPerConfigDirection: number
  maxConcurrentOperations: number
  autoRestartOnErrors: boolean
  logLevel: string
  maxDatabaseSizeMB: number
  databaseThresholdPercent: number
  automaticDatabaseCleanup: boolean
  automaticDatabaseBackups: boolean
  backupInterval: string
  minimumConnectIntervalMs: number
  symbolsPerExchange: number
  defaultMarginType: string
  defaultPositionMode: string
  rateLimitDelayMs: number
  maxConcurrentConnections: number
  enableTestnetByDefault: boolean
  logsLevel: string
  logsCategory: string
  logsLimit: number
  enableSystemMonitoring: boolean
  metricsRetentionDays: number
  mainEngineEnabled: boolean
  presetEngineEnabled: boolean
  maxPositionsPerExchange: Record<string, number>
  mainSymbols: string[]
  forcedSymbols: string[]
  useMainSymbols: boolean
  symbolOrderType: string
  indication_time_interval: number
  indication_range_min: number
  indication_range_max: number
  indication_min_profit_factor: number
  strategy_time_interval: number
  strategy_min_profit_factor: number
  stepRelationMinRatio: number
  stepRelationMaxRatio: number
  block_enabled: boolean
  dca_enabled: boolean
  marketActivityEnabled: boolean
  marketActivityCalculationRange: number
  marketActivityPositionCostRatio: number
  directionEnabled: boolean
  directionInterval: number
  directionTimeout: number
  directionRangeFrom: number
  directionRangeTo: number
  moveEnabled: boolean
  moveInterval: number
  moveTimeout: number
  activeEnabled: boolean
  activeInterval: number
  activeTimeout: number
  optimalCoordinationEnabled: boolean
  trailingOptimalRanges: boolean
  simultaneousTrading: boolean
  positionIncrementAfterSituation: boolean
  // Common Indicators - RSI
  rsiEnabled: boolean
  rsiPeriod: number
  rsiOversold: number
  rsiOverbought: number
  rsiPeriodFrom: number
  rsiPeriodTo: number
  rsiPeriodStep: number
  rsiOversoldFrom: number
  rsiOversoldTo: number
  rsiOversoldStep: number
  rsiOverboughtFrom: number
  rsiOverboughtTo: number
  rsiOverboughtStep: number
  // Common Indicators - MACD
  macdEnabled: boolean
  macdFastPeriod: number
  macdSlowPeriod: number
  macdSignalPeriod: number
  macdFastPeriodFrom: number
  macdFastPeriodTo: number
  macdFastPeriodStep: number
  macdSlowPeriodFrom: number
  macdSlowPeriodTo: number
  macdSlowPeriodStep: number
  macdSignalPeriodFrom: number
  macdSignalPeriodTo: number
  macdSignalPeriodStep: number
  // Common Indicators - Bollinger Bands
  bollingerEnabled: boolean
  bollingerPeriod: number
  bollingerStdDev: number
  bollingerPeriodFrom: number
  bollingerPeriodTo: number
  bollingerPeriodStep: number
  bollingerStdDevFrom: number
  bollingerStdDevTo: number
  bollingerStdDevStep: number
  // Common Indicators - EMA (Exponential Moving Average)
  emaEnabled: boolean
  emaShortPeriod: number
  emaLongPeriod: number
  emaShortPeriodFrom: number
  emaShortPeriodTo: number
  emaShortPeriodStep: number
  emaLongPeriodFrom: number
  emaLongPeriodTo: number
  emaLongPeriodStep: number
  // Common Indicators - SMA (Simple Moving Average)
  smaEnabled: boolean
  smaShortPeriod: number
  smaLongPeriod: number
  smaShortPeriodFrom: number
  smaShortPeriodTo: number
  smaShortPeriodStep: number
  smaLongPeriodFrom: number
  smaLongPeriodTo: number
  smaLongPeriodStep: number
  // Common Indicators - Stochastic
  stochasticEnabled: boolean
  stochasticKPeriod: number
  stochasticDPeriod: number
  stochasticSlowing: number
  stochasticKPeriodFrom: number
  stochasticKPeriodTo: number
  stochasticKPeriodStep: number
  stochasticDPeriodFrom: number
  stochasticDPeriodTo: number
  stochasticDPeriodStep: number
  stochasticSlowingFrom: number
  stochasticSlowingTo: number
  stochasticSlowingStep: number
  // Common Indicators - ADX (Average Directional Index)
  adxEnabled: boolean
  adxPeriod: number
  adxThreshold: number
  adxPeriodFrom: number
  adxPeriodTo: number
  adxPeriodStep: number
  adxThresholdFrom: number
  adxThresholdTo: number
  adxThresholdStep: number
  // Common Indicators - ATR (Average True Range)
  atrEnabled: boolean
  atrPeriod: number
  atrMultiplier: number
  atrPeriodFrom: number
  atrPeriodTo: number
  atrPeriodStep: number
  atrMultiplierFrom: number
  atrMultiplierTo: number
  atrMultiplierStep: number
  // Parabolic SAR
  parabolicSAREnabled: boolean
  parabolicSARAcceleration: number
  parabolicSARMaximum: number
  parabolicSARAccelerationFrom: number
  parabolicSARAccelerationTo: number
  parabolicSARAccelerationStep: number
  parabolicSARMaximumFrom: number
  parabolicSARMaximumTo: number
  parabolicSARMaximumStep: number
  autoRestartOnError: boolean
  restartCooldownMinutes: number
  maxRestartAttempts: number
  min_volume_enforcement: boolean
  exchangeDirectionEnabled: boolean
  exchangeMoveEnabled: boolean
  exchangeActiveEnabled: boolean
  exchangeOptimalEnabled: boolean
  exchangeBaseStrategyEnabled: boolean
  exchangeMainStrategyEnabled: boolean
  exchangeRealStrategyEnabled: boolean
  exchangeTrailingEnabled: boolean
  exchangeBlockEnabled: boolean
  exchangeDcaEnabled: boolean
  // Main Trade Specific Settings
  profitFactorMinMain?: number
  drawdownTimeMain?: number
  mainDirectionEnabled?: boolean
  mainMoveEnabled?: boolean
  mainActiveEnabled?: boolean
  mainOptimalEnabled?: boolean
  mainTrailingStrategy?: boolean
  mainBlockStrategy?: boolean
  mainDcaStrategy?: boolean
  // Preset Trade Specific Settings
  profitFactorMinPreset?: number
  drawdownTimePreset?: number
  presetTrailingEnabled?: boolean
  presetBlockEnabled?: boolean
  presetDcaEnabled?: boolean
  presetDirectionEnabled?: boolean
  presetMoveEnabled?: boolean
  presetActiveEnabled?: boolean
  presetOptimalEnabled?: boolean
  presetTrailingStrategy?: boolean
  presetBlockStrategy?: boolean
  presetDcaStrategy?: boolean
  // Trade Mode
  tradeMode?: string
  // Exchange Position Cost
  exchangePositionCost?: number
  // Volume Factor Settings
  baseVolumeFactorLive?: number
  baseVolumeFactorPreset?: number
  // Strategy Configuration Settings
  strategyTrailingEnabled?: boolean
  strategyBlockEnabled?: boolean
  strategyDcaEnabled?: boolean
  // Indication Configuration Settings
  directionRangeStep: number
  directionDrawdownValues: string // comma-separated: "10,20,30,40,50"
  directionMarketChangeFrom: number
  directionMarketChangeTo: number
  directionMarketChangeStep: number
  directionMinCalcTime: number
  directionLastPartRatio: number
  directionRatioFactorFrom: number
  directionRatioFactorTo: number
  directionRatioFactorStep: number

  moveRangeFrom: number
  moveRangeTo: number
  moveRangeStep: number
  moveDrawdownValues: string
  moveMarketChangeFrom: number
  moveMarketChangeTo: number
  moveMarketChangeStep: number
  moveMinCalcTime: number
  moveLastPartRatio: number
  moveRatioFactorFrom: number
  moveRatioFactorTo: number
  moveRatioFactorStep: number

  activeRangeFrom: number
  activeRangeTo: number
  activeRangeStep: number
  activeDrawdownValues: string
  activeMarketChangeFrom: number
  activeMarketChangeTo: number
  activeMarketChangeStep: number
  activeMinCalcTime: number
  activeLastPartRatio: number
  activeRatioFactorFrom: number
  activeRatioFactorTo: number
  activeRatioFactorStep: number
  activeCalculatedFrom: number
  activeCalculatedTo: number
  activeCalculatedStep: number
  activeLastPartFrom: number
  activeLastPartTo: number
  activeLastPartStep: number

  database_type: string
  database_url: string
}

export interface SettingsTabProps {
  settings: Settings
  handleSettingChange: (key: keyof Settings, value: any) => void
}
